name: dev-npm-publish

on:
  push:
    branches:
      - "main"

jobs:
  dev-npm-publish:
    name: dev-npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Resolve version
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Version based on commit: 0.0.0-dev.${{ steps.vars.outputs.sha_short }}"
        run: npm version 0.0.0-dev.${{ steps.vars.outputs.sha_short }} --force --no-git-tag-version

      - name: Build and Test
        run: pnpm test && pnpm build

      - name: Publish Dev Release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          tag: dev
          access: public

      - name: Publish to Stackblitz
        run: pnpm pkg-pr-new publish
